name: Publish Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Core
        run: dotnet build StateMachineKit.Core/StateMachineKit.Core.csproj --configuration Release --no-restore

      - name: Pack Core
        run: dotnet pack StateMachineKit.Core/StateMachineKit.Core.csproj --configuration Release --no-build --output ./nupkg/core

      - name: Build Godot
        run: dotnet build StateMachineKit.Godot/StateMachineKit.Godot.csproj --configuration Release --no-restore

      - name: Pack Godot
        run: dotnet pack StateMachineKit.Godot/StateMachineKit.Godot.csproj --configuration Release --no-build --output ./nupkg/godot

      - name: Publish Core to NuGet.org
        run: dotnet nuget push ./nupkg/core/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish Godot to NuGet.org
        run: dotnet nuget push ./nupkg/godot/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
