name: Publish Only the Godot module to NuGet

on:
  push:
    tags:
      - 'godot-v*'

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Godot
        run: dotnet build StateMachineKit.Godot/StateMachineKit.Godot.csproj --configuration Release --no-restore

      - name: Pack Godot
        run: dotnet pack StateMachineKit.Godot/StateMachineKit.Godot.csproj --configuration Release --no-build --output ./nupkg/godot

      - name: Publish Godot to NuGet.org
        run: dotnet nuget push ./nupkg/godot/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

